name: Docker Image CI

on:
  push:
    branches: [ "2.x" ]
  pull_request:
    branches: [ "2.x" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd docker; docker build . --file Dockerfile --tag farmos:$(date +%s)
